INSERT INTO SKILL(name) VALUES ('Java');
INSERT INTO SKILL(name) VALUES ('PHP');
INSERT INTO SKILL(name) VALUES ('C++');
INSERT INTO SKILL(name) VALUES ('C#');
INSERT INTO SKILL(name) VALUES ('ObjectC');
INSERT INTO SKILL(name) VALUES ('Python');
INSERT INTO SKILL(name) VALUES ('JavaScript');
INSERT INTO SKILL(name) VALUES ('Kotlin');
INSERT INTO SKILL(name) VALUES ('Scala');
INSERT INTO SKILL(name) VALUES ('HTML5');
INSERT INTO SKILL(name) VALUES ('CSS3');
INSERT INTO SKILL(name) VALUES ('WORDPRESS');

INSERT INTO ACCOUNT(login,password,account_status) value ("kiki","koko","ACTIVE");
INSERT INTO DEVELOPER(name, account_id) value ("Kola",1);